encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"

urlpatterns = [
    path("", views.index, name="index"),
    path("page",views.page, name="page"),
    path("create", views.create, name="create"),
    path("<str:flag>/createpage", views.createpage, name="createpage"),
    path("random", views.random, name="random"),
    path("<str:entry>/",views.entry, name="entry"),
    path("<str:entry>/edit", views.edit, name = "edit")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('encyclopedia/', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render,redirect
from . import util
from markdown2 import Markdown
from random import sample

entries = {}

def index(request):
    for i in util.list_entries():
        entries[i.lower()] = util.get_entry(i)
    l = []
    for i in util.list_entries():
        l.append(i)
    return render(request, "encyclopedia/index.html", {
        "entries": l
    })

def page(request):
    path = "/encyclopedia/"+request.GET.get("page")+"/"
    return redirect(path)

def entry(request,entry):
    markdowner = Markdown()
    if util.get_entry(entry) == None:
        return render(request, "encyclopedia/error.html",{
            "msg": "Page not found !"
        })
    return render(request, "encyclopedia/page.html",{
        "page": markdowner.convert(entries[entry.lower()]),
        "entry": entry
    })

def create(request):
    return render(request,"encyclopedia/create.html")

def createpage(request, flag):
    title = request.GET.get("title")
    if title in util.list_entries() and flag == "True":
        return render(request, "encyclopedia/error.html",{
            "msg": "A page with the same name already exisits !"
        })
    else:
        markdowner = Markdown()
        util.save_entry(title,request.GET.get("content"))
        entries[title.lower()] = util.get_entry(title)
        path = "/encyclopedia/"+title+"/"
        return redirect(path, {
            "page": markdowner.convert(util.get_entry(title)),
            "entry": title
        })

def edit(request, entry):
    if not entry.lower() in entries:
        return render(request, "encyclopedia/error.html", {
            "msg": "Invalid Request !"
        })
    content = entries[entry.lower()]
    content = content[content.index("\n")+1:]
    return render(request, "encyclopedia/edit.html", {
        "title": entry,
        "content": content
    })

def random(request):
    l = []
    for i in entries:
        l.append(i)
    path = "/encyclopedia/"+(sample(l,1)[0])+"/"
    return redirect(path)

encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create a Page
{% endblock %}

{% block body %}
    <h1>Create a page:</h1>
    <form action="{% url 'encyclopedia:createpage' %}" method="GET">
        <input type="text" name="title" placeholder="Enter the title of page">
        <input type="text" name="content" placeholder="Enter content">
        <input type="submit">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit a Page
{% endblock %}

{% block body %}

    {% with flag="False" %}

    <h1>Edit a page:</h1>
    <form action="{% url 'encyclopedia:createpage' flag %}" method="GET">
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Title:</label>
            <input type="text" value={{title}} class="form-control" id="exampleFormControlInput1" name = "title" placeholder="Enter the title of the page" readonly>
          </div>
          <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Content:</label>
            <textarea class="form-control" id="exampleFormControlTextarea1" name = "content" rows="5" placeholder="Enter the content">{{ content }}</textarea>
          </div>
          <div class="mb-3">
            <button type="submit" class="btn btn-primary mb-3">Save</button>
          </div>
    </form>

    {% endwith %}
{% endblock %}

encyclopedia/templates/encyclopedia/error.html
<!DOCTYPE html>
<head>
    <title>Error!</title>
</head>
<body>
    <h1>{{ msg }}</h1>
</body>

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{{ entry }}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action = "{% url 'encyclopedia:page' %}" method="GET">
                    {% csrf_token %}
                    <input class="search" type="text" name="page" placeholder="Search Encyclopedia">
                    <input type="submit">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/page.html
{% extends "encyclopedia/layout.html" %}
{% load static %}

{% block title %}
    {{ entry }}
{% endblock %}

{% block body %}
    <div class = "edit_button">
        <a href="{% url 'encyclopedia:edit' entry %}">Edit page</a>
    </div>    
    {{ page|safe }}
{% endblock %}